services:
  backend:
    build: 
       context: .
       dockerfile: Dockerfile
    container_name: sentinel_xdr_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./scripts:/app/scripts
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ./scripts/start.sh

  db:
    image: postgres:15
    container_name: sentinel_xdr_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: sentinel_xdr_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: 
       context: .
       dockerfile: Dockerfile
    container_name: sentinel_xdr_migrate
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ./scripts/run-migrations.sh
    profiles:
      - migration

volumes:
  postgres_data:
    driver: local
