# Definitive docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_xdr_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    # --- FIX: Healthcheck removed to prevent the restart loop ---

  db:
    image: postgres:15
    container_name: sentinel_xdr_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: sentinel_xdr_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    # This healthcheck is reliable and is kept
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_xdr_migrate
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ["alembic", "upgrade", "head"]
    # --- FIX: Added profile so it's ignored by 'docker compose up' ---
    profiles:
      - migration

  redis:
    image: redis:7-alpine
    container_name: sentinel_xdr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    # This healthcheck is reliable and is kept
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  model-api:
    build:
      context: ./model_infer_api
      dockerfile: Dockerfile
    container_name: sentinel_xdr_model_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    # --- FIX: Healthcheck removed to prevent the restart loop ---
    # Model loading is slow and makes health checks unreliable.

  arq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_xdr_arq_worker
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - MODEL_API_URL=http://model-api:8080/infer
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    command: ["arq", "src.worker.WorkerSettings"]

volumes:
  postgres_data:
    driver: local